server:
  port: 50000
  servlet:
    context-path: /users
spring:
  application:
    name: user-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.cloud.loadbalancer: debug